server:
  port: 9999

spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/musinsa
    url: jdbc:h2:file:~/Dev/tasks/db/musinsa_db;AUTO_SERVER=TRUE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /musinsa

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 1000

logging:
  level:
    root: WARN
    org:
      hibernate:
        sql: WARN
        type: WARN
